### ISSUE TITLE
Add more fork options

### ISSUE THREAD

**Issue by ProLoser** [musically-ut/lovely-forks#21]
I've been wanting to add something like this for a while to my [Github Omnibox extension](https://chrome.google.com/webstore/detail/omnibox-for-github/jbfhklldhgbomclinhlgbmjjiimafolo) any interest in merging efforts?

Anyway, I think it'd be nice if you didn't limit suggestions to only the primary fork, but continue showing forks everywhere. Also, I might change the text and suggestion to be a bit more informative like "also a popular fork: [x/y]()" for the fork with the second-highest stars and "also an active fork: [x/y]()" for the one with the most recent commit(s). It would be nice if it could also count the number of commits. The flame icon doesn't really illustrate much. You would be able to combine them asl: "also a popular active fork: [x/y]()"

I think it'd also be cool if it was a dropdown (on hover) maybe triggered by an ellipses or down arrow that lets you see the top 3-5 most popular / active forks?

My chrome extension adds a dropdown so it's not too difficult:
<img width="734" alt="screen shot 2016-03-16 at 11 48 11 am" src="https://cloud.githubusercontent.com/assets/67395/13824843/0ad842ae-eb6d-11e5-8751-0e6e4d1e7da5.png">

**Comment by musically-ut** [comment]
Thanks for the suggestions. Omnibox is a great extension! :)

Responses inline.

----

> any interest in merging efforts?

I am ambivalent about the merge. With recent changes to Chrome, the extensions have become obnoxiously visible and it is better to keep them to a minimum. However, on the other hand, I would like to maintain Firefox compatibility. So I would wait for a bit to see how the extension ecosystem evolves. Or, we could attempt to abstract out the functioning and keep it at both places. Suggestions?

> Anyway, I think it'd be nice if you didn't limit suggestions to only the primary fork, but continue showing forks everywhere.

The UI was the primary problem, though I've found that the community usually converges to only one maintained fork. I like your suggestion about creating a small hover card showing the other forks in order of stargazers. However, getting the recency information about those other forks leads me to the second point.

>  "also an active fork: x/y" for the one with the most recent commit(s).
>  ... It would be nice if it could also count the number of commits. 

At the moment, I am using Github's [compare API](https://developer.github.com/v3/repos/commits/#compare-two-commits) to determine if the `default` branch of the fork is ahead of the same branch on the `origin`, i.e., the difference between number of `ahead_by` commits and number of `behind_by` commits is positive. This is, at best, a guess which [Ivan](https://github.com/izuzak) suggested since the other pieces of information about recency of repositories provided by Github API [are misleading](https://github.com/musically-ut/lovely-forks/issues/13#issuecomment-187831632). I am not sure whether I would show these numbers because of they are, after all, an heuristic. Also, it may change, as it already has from comparing the time of the recent commits to comparing pushed at times to counting commits.

Additionally, Lovely Forks does not, at the moment, allow for Github authentication. It uses two API calls for each Github page (and caches results): one to get the list of forks ordered by `stargazers` (which is sufficient for showing a list of active forks) and the second to the compare API to guess the recency. Adding more API calls to determine improved recency information is not very alluring, especially if the information is going to be hard to interpret/use anyway.

----

What did you mean by **"x/y"**?

**Comment by ProLoser** [comment]
Owner/repo

**Comment by bfred-it** [comment]
> any interest in merging efforts?

The two extensions are completely separate. You can merge efforts by cross-contributing but it doesn't make sense to merge just to save an icon (which can be hidden anyway)

> Anyway, I think it'd be nice if you didn't limit suggestions to only the primary fork, but continue showing forks everywhere.

If you want to see more forks, you can click the fork button <img width="275" alt="" src="https://user-images.githubusercontent.com/1402241/28512345-1e9ed0e4-7084-11e7-82d7-c180abefe681.png"> or add a link to the [members page](https://github.com/musically-ut/lovely-forks/network/members)

**Comment by musically-ut** [comment]
Now there is useful-forks.github.io to solve the same problem.
