### ISSUE TITLE
"also forked to" disappears after navigating from main repo page & back again

### ISSUE THREAD

**Issue by swrobel** [musically-ut/lovely-forks#50]
Firefox 78
Lovely Forks 3.4.0

Fresh page load:
<img width="225" alt="Screen Shot 2020-06-16 at 7 52 44 AM" src="https://user-images.githubusercontent.com/157270/84790639-6d376400-afa6-11ea-98e0-8634ffb834e7.png">

Click Issues tab:
<img width="219" alt="Screen Shot 2020-06-16 at 7 52 50 AM" src="https://user-images.githubusercontent.com/157270/84790653-71fc1800-afa6-11ea-8072-e44c1c9b301e.png">

Click Code tab:
<img width="226" alt="Screen Shot 2020-06-16 at 7 52 33 AM" src="https://user-images.githubusercontent.com/157270/84790678-77f1f900-afa6-11ea-9041-b43fd9c4c97e.png">

**Comment by musically-ut** [comment]
Thanks for the report!

The issue was reported earlier at #43 

GitHub has been changing which page transitions are done using `pjax` and which are actual page-reloads. The `pjax` capture proposed by Mottie didn't work locally on my system when I tried the fix, but I haven't investigated it in full detail yet.

I'll pick it up again once I have some time, perhaps over the weekend.

**Comment by musically-ut** [comment]
This should also have been fixed as part of #63
